name: 'Build and populate cache'
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    # rebuild everyday at 2:51
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron: '35 4 * * *'
jobs:
  build-packages:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux
        ci-command:
          - ci
          - ci-cuda
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name as used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - <YOUR_REPO_NAME>
        # Set this to cache your build results in cachix for faster builds
        # in CI and for everyone who uses your cache.
        #
        # Format: Your cachix cache host name without the ".cachix.org" suffix.
        # Example: mycache (for mycache.cachix.org)
        #
        # For this to work, you also need to set the CACHIX_SIGNING_KEY or
        # CACHIX_AUTH_TOKEN secret in your repository secrets settings in
        # Github found at
        # https://github.com/Program-Learning/nur-packages/settings/secrets
        cachixName:
          - dataeraserc
        atticName:
          # - <YOUR_ATTIC_NAME>
          - lantian
        atticEndpoint:
          # - <YOUR_ATTIC_ENDPOINT>
          - https://attic.xuyh0120.win
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
          # - nixpkgs=channel:nixos-23.05

    runs-on: ubuntu-latest
    env:
      GIT_SSL_NO_VERIFY: 'true'
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          build-mount-path: '/nix'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMERGE_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: "${{ matrix.nixPath }}"
          extra_nix_config: |
            experimental-features = nix-command flakes ca-derivations
            extra-experimental-features = nix-command flakes ca-derivations
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = i686-linux aarch64-linux arm-linux
            keep-going = true
            log-lines = 25
            substituters = https://nix-community.cachix.org https://cache.garnix.io https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
            trusted-substituters = https://nix-community.cachix.org https://cache.garnix.io https://cache.nixos.org/

      - name: Speed Up nix
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        # Don't replace <YOUR_CACHIX_NAME> here!
        if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
        with:
          name: ${{ matrix.cachixName }}
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        if: ${{ matrix.atticName != '<YOUR_ATTIC_NAME>' && matrix.atticEndpoint != '<YOUR_ATTIC_ENDPOINT>' }}
        continue-on-error: true
        with:
          endpoint: ${{ matrix.atticEndpoint }}
          cache: ${{ matrix.atticName }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Set nix daemon tmpdir path
        run: |
          sudo mkdir -p /nix/tmpdir
          sudo chown "$(whoami)" /nix/tmpdir

          cat > override.conf <<EOF
          [Service]
          Environment="TMPDIR=/nix/tmpdir"
          EOF
          sudo mkdir /etc/systemd/system/nix-daemon.service.d/
          sudo mv override.conf /etc/systemd/system/nix-daemon.service.d/override.conf
          sudo systemctl daemon-reload
          sudo systemctl restart nix-daemon

      - name: Build nix packages
        run: |
          echo "::group::Preparing"
          env TMPDIR=/nix/tmpdir nix run .#${{ matrix.ci-command }} -- ${{ matrix.system }}

      - name: Commit back to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ success() || failure() }}
        with:
          commit_message: 'auto: update package hashes'

  test-nur-eval:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name as used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - <YOUR_REPO_NAME>
        # Set this to cache your build results in cachix for faster builds
        # in CI and for everyone who uses your cache.
        #
        # Format: Your cachix cache host name without the ".cachix.org" suffix.
        # Example: mycache (for mycache.cachix.org)
        #
        # For this to work, you also need to set the CACHIX_SIGNING_KEY or
        # CACHIX_AUTH_TOKEN secret in your repository secrets settings in
        # Github found at
        # https://github.com/Program-Learning/nur-packages/settings/secrets
        cachixName:
          - dataeraserc
        atticName:
          # - <YOUR_ATTIC_NAME>
          - lantian
        atticEndpoint:
          # - <YOUR_ATTIC_ENDPOINT>
          - https://attic.xuyh0120.win
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
          # - nixpkgs=channel:nixos-23.05
    runs-on: ubuntu-latest
    env:
      GIT_SSL_NO_VERIFY: 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: "${{ matrix.nixPath }}"
          extra_nix_config: |
            experimental-features = nix-command flakes ca-derivations
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = i686-linux aarch64-linux arm-linux
      - name: Speed Up nix
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build nix packages
        if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
        run: |
          nix run .#nur-check

  check-package-meta:
    runs-on: ubuntu-latest
    env:
      GIT_SSL_NO_VERIFY: 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes ca-derivations
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = i686-linux aarch64-linux arm-linux
      - name: Build nix packages
        run: |
          tools/check_package_meta.py

  update-nur:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name as used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - <YOUR_REPO_NAME>
        # Set this to cache your build results in cachix for faster builds
        # in CI and for everyone who uses your cache.
        #
        # Format: Your cachix cache host name without the ".cachix.org" suffix.
        # Example: mycache (for mycache.cachix.org)
        #
        # For this to work, you also need to set the CACHIX_SIGNING_KEY or
        # CACHIX_AUTH_TOKEN secret in your repository secrets settings in
        # Github found at
        # https://github.com/Program-Learning/nur-packages/settings/secrets
        cachixName:
          - dataeraserc
        atticName:
          # - <YOUR_ATTIC_NAME>
          - lantian
        atticEndpoint:
          # - <YOUR_ATTIC_ENDPOINT>
          - https://attic.xuyh0120.win
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
          # - nixpkgs=channel:nixos-23.05
    runs-on: ubuntu-latest
    needs:
      - build-packages
      - test-nur-eval
      - check-package-meta
    steps:
      - name: Trigger NUR update
        # Don't replace <YOUR_REPO_NAME> here!
        if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"

  update-flakehub:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name sas used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - <YOUR_REPO_NAME>
        # Set this to cache your build results in cachix for faster builds
        # in CI and for everyone who uses your cache.
        #
        # Format: Your cachix cache host name without the ".cachix.org" suffix.
        # Example: mycache (for mycache.cachix.org)
        #
        # For this to work, you also need to set the CACHIX_SIGNING_KEY or
        # CACHIX_AUTH_TOKEN secret in your repository secrets settings in
        # Github found at
        # https://github.com/Program-Learning/nur-packages/settings/secrets
        cachixName:
          - dataeraserc
        atticName:
          # - <YOUR_ATTIC_NAME>
          - lantian
        atticEndpoint:
          # - <YOUR_ATTIC_ENDPOINT>
          - https://attic.xuyh0120.win
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
          # - nixpkgs=channel:nixos-23.05
    runs-on: ubuntu-latest
    needs:
      - build-packages
      # - test-nur-eval
      - check-package-meta
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'DeterminateSystems/nix-installer-action@main'
      - uses: 'DeterminateSystems/flakehub-push@main'
        with:
          name: 'DataEraserC/nur-packages'
          rolling: true
          visibility: 'public'
          include-output-paths: false
